import type { Track, VoiceId } from '../engine';

/**
 * Historical rhythm presets adapted for Euclidean Groove Lab.
 * Each preset is a complete 4-track kit derived from authentic rhythmic traditions.
 *
 * Source: Toussaint, "The Geometry of Musical Rhythm"
 * Rhythm patterns extracted as interonset intervals [k-n notation]
 */

export interface RhythmPreset {
  id: string;
  name: string;
  description: string;
  source_rhythm?: string;
  source_pattern?: number[];
  authenticity?: number; // 1-5 stars
  tracks: Track[];
}

// Preset collection - ready for import into groove lab state
// Load via: import(rhythmPresets) and replace current tracks
export const rhythmPresets: RhythmPreset[] = [
  {
    id: 'shiko-kit',
    name: 'Shiko Kit',
    description: 'Afro-Cuban hybrid from Shiko rhythm [4-2-4-2-4]',
    source_rhythm: 'Shiko',
    source_pattern: [4, 2, 4, 2, 4],
    authenticity: 4,
    tracks: [
      {
        id: 'kick',
        name: 'Kick',
        color: '#c084fc',
        steps: 16,
        hits: 3,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'kick' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'snare',
        name: 'Snare',
        color: '#f472b6',
        steps: 16,
        hits: 1,
        rotation: 5,
        mute: false,
        solo: false,
        voiceId: 'snare' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'hat',
        name: 'Hat',
        color: '#60a5fa',
        steps: 16,
        hits: 8,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'hat' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
        velocity: [100, 85, 100, 85, 100, 85, 100, 85],
      },
      {
        id: 'bass',
        name: 'Bass',
        color: '#34d399',
        steps: 16,
        hits: 1,
        rotation: 3,
        mute: false,
        solo: false,
        voiceId: 'bass' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
    ],
  },
  {
    id: 'clave-son-kit',
    name: 'Clave Son Kit',
    description: 'Afro-Cuban foundation [3-3-4-2-4] - Bo Diddley beat',
    source_rhythm: 'Clave Son',
    source_pattern: [3, 3, 4, 2, 4],
    authenticity: 5,
    tracks: [
      {
        id: 'kick',
        name: 'Kick',
        color: '#c084fc',
        steps: 16,
        hits: 4,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'kick' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'snare',
        name: 'Snare',
        color: '#f472b6',
        steps: 16,
        hits: 3,
        rotation: -4,
        mute: false,
        solo: false,
        voiceId: 'snare' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'hat',
        name: 'Hat',
        color: '#60a5fa',
        steps: 16,
        hits: 8,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'hat' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
        velocity: [100, 85, 100, 85, 100, 85, 100, 85],
      },
      {
        id: 'bass',
        name: 'Bass',
        color: '#34d399',
        steps: 16,
        hits: 3,
        rotation: 1,
        mute: false,
        solo: false,
        voiceId: 'bass' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
    ],
  },
  {
    id: 'tresillo-kit',
    name: 'Tresillo Kit',
    description: 'Cuban Tresillo foundation [3-3-2] - reggaeton core',
    source_rhythm: 'Tresillo',
    source_pattern: [3, 3, 2],
    authenticity: 5,
    tracks: [
      {
        id: 'kick',
        name: 'Kick',
        color: '#c084fc',
        steps: 8,
        hits: 3,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'kick' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'snare',
        name: 'Snare',
        color: '#f472b6',
        steps: 8,
        hits: 3,
        rotation: 1,
        mute: false,
        solo: false,
        voiceId: 'snare' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'hat',
        name: 'Hat',
        color: '#60a5fa',
        steps: 8,
        hits: 4,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'hat' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
        velocity: [100, 80, 100, 80],
      },
      {
        id: 'bass',
        name: 'Bass',
        color: '#34d399',
        steps: 8,
        hits: 2,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'bass' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
    ],
  },
  {
    id: 'bossa-nova-kit',
    name: 'Bossa Nova Kit',
    description: 'Brazilian groove [3-3-4-3-3]',
    source_rhythm: 'Bossa-Nova',
    source_pattern: [3, 3, 4, 3, 3],
    authenticity: 4,
    tracks: [
      {
        id: 'kick',
        name: 'Kick',
        color: '#c084fc',
        steps: 16,
        hits: 5,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'kick' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'snare',
        name: 'Snare',
        color: '#f472b6',
        steps: 16,
        hits: 2,
        rotation: 6,
        mute: false,
        solo: false,
        voiceId: 'snare' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'hat',
        name: 'Hat',
        color: '#60a5fa',
        steps: 16,
        hits: 8,
        rotation: 2,
        mute: false,
        solo: false,
        voiceId: 'hat' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
        velocity: [100, 90, 100, 85, 100, 90, 100, 85],
      },
      {
        id: 'bass',
        name: 'Bass',
        color: '#34d399',
        steps: 16,
        hits: 3,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'bass' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
    ],
  },
  {
    id: 'west-african-bell-kit',
    name: 'West African Bell Kit',
    description: '12-pulse bell pattern [2-1-2-2-1-2-2]',
    source_rhythm: 'West African Bell Pattern',
    source_pattern: [2, 1, 2, 2, 1, 2, 2],
    authenticity: 4,
    tracks: [
      {
        id: 'kick',
        name: 'Kick',
        color: '#c084fc',
        steps: 12,
        hits: 5,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'kick' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'snare',
        name: 'Snare',
        color: '#f472b6',
        steps: 12,
        hits: 5,
        rotation: 1,
        mute: false,
        solo: false,
        voiceId: 'snare' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'hat',
        name: 'Hat',
        color: '#60a5fa',
        steps: 12,
        hits: 6,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'hat' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
        velocity: [100, 85, 95, 80, 100, 90],
      },
      {
        id: 'bass',
        name: 'Bass',
        color: '#34d399',
        steps: 12,
        hits: 4,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'bass' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
    ],
  },
  {
    id: 'gahu-kit',
    name: 'Gahu Kit',
    description: 'Ewe people rhythm [3-3-4-4-2]',
    source_rhythm: 'Gahu',
    source_pattern: [3, 3, 4, 4, 2],
    authenticity: 4,
    tracks: [
      {
        id: 'kick',
        name: 'Kick',
        color: '#c084fc',
        steps: 16,
        hits: 5,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'kick' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'snare',
        name: 'Snare',
        color: '#f472b6',
        steps: 16,
        hits: 2,
        rotation: 4,
        mute: false,
        solo: false,
        voiceId: 'snare' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'hat',
        name: 'Hat',
        color: '#60a5fa',
        steps: 16,
        hits: 8,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'hat' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
        velocity: [100, 80, 85, 95, 100, 85, 90, 100],
      },
      {
        id: 'bass',
        name: 'Bass',
        color: '#34d399',
        steps: 16,
        hits: 2,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'bass' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
    ],
  },
  {
    id: 'soukous-kit',
    name: 'Soukous Kit',
    description: 'Congolese rhythm [3-3-4-1-5]',
    source_rhythm: 'Soukous',
    source_pattern: [3, 3, 4, 1, 5],
    authenticity: 3,
    tracks: [
      {
        id: 'kick',
        name: 'Kick',
        color: '#c084fc',
        steps: 16,
        hits: 5,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'kick' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'snare',
        name: 'Snare',
        color: '#f472b6',
        steps: 16,
        hits: 4,
        rotation: 2,
        mute: false,
        solo: false,
        voiceId: 'snare' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'hat',
        name: 'Hat',
        color: '#60a5fa',
        steps: 16,
        hits: 8,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'hat' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
      {
        id: 'bass',
        name: 'Bass',
        color: '#34d399',
        steps: 16,
        hits: 3,
        rotation: 0,
        mute: false,
        solo: false,
        voiceId: 'bass' as const,
        volume: 100,
        playbackMode: 'forward',
        playbackSpeed: 1,
      },
    ],
  },
];

/**
 * Get a preset by ID. Returns undefined if not found.
 */
export function getRhythmPreset(id: string): RhythmPreset | undefined {
  return rhythmPresets.find((p) => p.id === id);
}

/**
 * Get all presets matching an authenticity threshold (1-5 stars).
 */
export function getPresetsByAuthenticity(minStars: number): RhythmPreset[] {
  return rhythmPresets.filter((p) => (p.authenticity || 0) >= minStars);
}

/**
 * Get presets suitable for a specific instrument.
 * Returns the full kits that include the given voiceId.
 */
export function getPresetsWithVoice(voiceId: VoiceId): RhythmPreset[] {
  return rhythmPresets.filter((p) =>
    p.tracks.some((t) => t.voiceId === voiceId),
  );
}
